### ISSUE TITLE
Uncaught TypeError: self.location.reload is not a function

### ISSUE THREAD

**Issue by nxvinh222** [lxieyang/chrome-extension-boilerplate-react#80]
I kept getting this error whenever i tried to save the project, the project working fine but any idea how to fix this?
![image](https://user-images.githubusercontent.com/35555098/142566410-f184aa06-dc71-405f-84c9-3e5c3dbc342a.png)

**Comment by leanderseige** [comment]
+1 I have the same problem

**Comment by KartikKumarSahoo** [comment]
+1

**Comment by ayushmz29** [comment]
Same issue with my project @lxieyang. I'm relatively new so I can't figure out the solution to this. Thank you.

**Comment by harbolaez** [comment]
Any update on this?

**Comment by estebanrao** [comment]
I'm seeing this error as well, not blocking development but still annoying

**Comment by polis80cy** [comment]
+1

**Comment by lxieyang** [comment]
should be fixed!

**Comment by polis80cy** [comment]
Still happening for me

<img width="594" alt="Screenshot 2022-02-05 at 6 29 03 PM" src="https://user-images.githubusercontent.com/14854276/152650091-b230de84-f6dd-4d01-87cd-08e4b4d3ec98.png">

**Comment by nxvinh222** [comment]
+1 still happening
